# Base WORKDIR => /
FROM openjdk:24-jdk-slim
RUN apt update
RUN apt install -y iputils-ping
# Set container run time path
WORKDIR /app

# Copy Jar from MAC to Ubunutu > /app
COPY sample-auth-service/target/auth-service-latest.jar auth-service.jar

# Run java -jar /app/api-gateway-docker-image-0.0.1.jar
CMD ["java", "-jar","auth-service.jar"]