FROM ubuntu:latest

# Create users
RUN useradd -m -u 1001 vaibhav
RUN useradd -m -u 1002 zodge

# Copy files
COPY appv /appv
COPY appz /appz

# Set ownership and permissions for vaibhav executable
RUN chown vaibhav:vaibhav /appv
RUN chmod 700 /appv

# Set ownership and permissions for zodge executable
RUN chown zodge:zodge /appz
RUN chmod 700 /appz

# Switch to zodge user
USER zodge

# Execute vaibhav command
CMD ["bash"]
