FROM ubuntu:latest

RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

COPY hello-service/target/hello-world-0.0.1-SNAPSHOT.jar hello-world.jar

ENTRYPOINT [ "java","-jar","hello-world.jar" ]

