filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
setup.kibana:
  host: "http://kibana:5601"

