apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
spec:
  containers:
  - name : api-gateway-1
    image: dnyanyog.org/api-gateway:latest
    imagePullPolicy: Never
  - name : api-gateway-2
    image: dnyanyog.org/api-gateway:latest
    imagePullPolicy: Never