apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: api-gateway  # Must match the labels in the pod template
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-1
        image: dnyanyog.org/api-gateway:latest
        livenessProbe:
          httpGet:
            path: /api/v1/healthy
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
          timeoutSeconds: 2
          failureThreshold: 3
        imagePullPolicy: Never
      - name: api-gateway-2
        image: dnyanyog.org/api-gateway:latest
        imagePullPolicy: Never
        env:
        - name: SERVER_PORT
          value: "8081"
