# Base WORKDIR => /
FROM ubuntu:latest

# Install jdk 17
RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

#Documentation
EXPOSE 8080

# Copy Jar from MAC to Ubunutu > /app
COPY hello-world-0.0.1-SNAPSHOT.jar hello-world.jar

ENTRYPOINT [ "java", "-jar","hello-world.jar"]  # CMD command can be overriden by docker run time parameters
CMD [ "a","b","c","d","e","f" ]
