groups:
  - name: spring-boot-alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 50% for more than 2 minutes."

      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) > 0.8
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High Heap Memory usage"
          description: "Heap memory usage is above 80% for more than 2 minutes."

      - alert: HTTP5xxErrors
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High number of HTTP 5xx errors"
          description: "{{ $value }} HTTP 5xx errors in the last 1 minutes."
