# Use an Ubuntu base image
FROM ubuntu:latest

# Update package lists and install build tools
RUN apt-get update && apt-get install -y \
    build-essential

RUN apt-get install -y bash
# Install bash
# Set the working directory
WORKDIR /usr/src/app

# Set the entry point to bash
ENTRYPOINT ["/bin/bash"]
