name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  do-pre-commit-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Google Java Formatter Check
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name: SonarQube Scan
      if: false 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=your_project_key -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      continue-on-error: true

    - name: OWASP Check
      if: false 
      run: mvn org.owasp:dependency-check-maven:check
      continue-on-error: true

    - name: OSS Check
      if: false 
      run: mvn ossindex:audit
      continue-on-error: true

    - run: mvn clean install docker:build
    - name: Tag Docker image
      run: |
        REPO_NAME=$(basename $(pwd))
        docker tag dnyanyog.org/$REPO_NAME:latest ${{secrets.DOCKER_REGISTRY_USER}}/$REPO_NAME:$GITHUB_REF_NAME
        docker images          
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.GH_TOKEN }} 
    - name: Push Docker image to GitHub Packages
      run: |
        REPO_NAME=$(basename $(pwd))
        docker push ${{ secrets.DOCKER_REGISTRY_USER }}/$REPO_NAME:$GITHUB_REF_NAME