name: Learn GitHub Actions

on:
  push:
    branches:
      - master

env:
  OWNER_NAME: "Vaibhav"

jobs:
  color-selector:
    runs-on: ubuntu-latest
    outputs:
      SELECTED_COLOR: ${{ steps.set_color.outputs.SELECTED_COLOR }}
    steps:
      - name: Set color
        id: set_color
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

  consume:
    runs-on: ubuntu-latest
    needs: color-selector
    steps:
      - name: Get color
        run: echo "Running by $OWNER_NAME - The selected color is ${{ needs.color-selector.outputs.SELECTED_COLOR }}"