name: Context Variables Example

on:
  push:
    branches:
      - master
env:
  GLOBAL_ENV_VAR: "global-value"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Display environment variable
        run: echo "Global ENV VAR - ${{ env.GLOBAL_ENV_VAR }}"

      - name: Display GitHub context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Workflow: ${{ github.ref_name }}"
          echo "Run ID: ${{ github.github.ref_name }}"

  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.0, 2.0]
    steps:
      - name: Display matrix variable
        run: echo "Matrix Version- ${{ matrix.version }}"

  runner-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display runner information
        run: echo "Running on- ${{ runner.os }}"

  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display runner information
        run: echo "Running on- ${{ secrets.user_password }}"