name: Use container for a job

on:
  push:
    branches:
      -  master
jobs:
  build:
    #GitHub Hosted runner
    runs-on: ubuntu-latest 
    container:
      image: alpine:latest
    steps:
      - name: print hellow
        run: cat /etc/os-release
        continue-on-error: true
